// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7uNbtKnDZaeZxcbENkTRwXRtfqaO7K50',
    appId: '1:346891596666:web:c9e42b311d7941f405dcc3',
    messagingSenderId: '346891596666',
    projectId: 'tiktokmini-33952',
    authDomain: 'tiktokmini-33952.firebaseapp.com',
    storageBucket: 'tiktokmini-33952.firebasestorage.app',
    measurementId: 'G-12X56PL8P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAen5skoPzH3jav-Gx84fxbMjCCQoAf3c8',
    appId: '1:346891596666:android:3c77c42f6301c33605dcc3',
    messagingSenderId: '346891596666',
    projectId: 'tiktokmini-33952',
    storageBucket: 'tiktokmini-33952.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB64wFuG6V29g4jzGAQsGo0WzlyriHKq2w',
    appId: '1:346891596666:ios:83793954be3865a605dcc3',
    messagingSenderId: '346891596666',
    projectId: 'tiktokmini-33952',
    storageBucket: 'tiktokmini-33952.firebasestorage.app',
    iosBundleId: 'com.example.tiktokClonerMini',
  );
}
